// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: shared/proto/packets.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_StateUpdate
	//	*ClientEvent_Hit
	//	*ClientEvent_Fire
	//	*ClientEvent_Reload
	//	*ClientEvent_SwitchWeapon
	//	*ClientEvent_RespawnRequest
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetStateUpdate() *PlayerStateUpdate {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_StateUpdate); ok {
			return x.StateUpdate
		}
	}
	return nil
}

func (x *ClientEvent) GetHit() *HitEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Hit); ok {
			return x.Hit
		}
	}
	return nil
}

func (x *ClientEvent) GetFire() *FireEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Fire); ok {
			return x.Fire
		}
	}
	return nil
}

func (x *ClientEvent) GetReload() *ReloadEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *ClientEvent) GetSwitchWeapon() *SwitchWeaponEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_SwitchWeapon); ok {
			return x.SwitchWeapon
		}
	}
	return nil
}

func (x *ClientEvent) GetRespawnRequest() *RespawnRequestEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_RespawnRequest); ok {
			return x.RespawnRequest
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_StateUpdate struct {
	StateUpdate *PlayerStateUpdate `protobuf:"bytes,1,opt,name=state_update,json=stateUpdate,proto3,oneof"`
}

type ClientEvent_Hit struct {
	Hit *HitEvent `protobuf:"bytes,2,opt,name=hit,proto3,oneof"`
}

type ClientEvent_Fire struct {
	Fire *FireEvent `protobuf:"bytes,3,opt,name=fire,proto3,oneof"`
}

type ClientEvent_Reload struct {
	Reload *ReloadEvent `protobuf:"bytes,4,opt,name=reload,proto3,oneof"`
}

type ClientEvent_SwitchWeapon struct {
	SwitchWeapon *SwitchWeaponEvent `protobuf:"bytes,5,opt,name=switch_weapon,json=switchWeapon,proto3,oneof"`
}

type ClientEvent_RespawnRequest struct {
	RespawnRequest *RespawnRequestEvent `protobuf:"bytes,6,opt,name=respawn_request,json=respawnRequest,proto3,oneof"`
}

func (*ClientEvent_StateUpdate) isClientEvent_Event() {}

func (*ClientEvent_Hit) isClientEvent_Event() {}

func (*ClientEvent_Fire) isClientEvent_Event() {}

func (*ClientEvent_Reload) isClientEvent_Event() {}

func (*ClientEvent_SwitchWeapon) isClientEvent_Event() {}

func (*ClientEvent_RespawnRequest) isClientEvent_Event() {}

type PlayerStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rx            float32                `protobuf:"fixed32,4,opt,name=rx,proto3" json:"rx,omitempty"` // rotation quaternion x
	Ry            float32                `protobuf:"fixed32,5,opt,name=ry,proto3" json:"ry,omitempty"` // rotation quaternion y
	Rz            float32                `protobuf:"fixed32,6,opt,name=rz,proto3" json:"rz,omitempty"` // rotation quaternion z
	Rw            float32                `protobuf:"fixed32,7,opt,name=rw,proto3" json:"rw,omitempty"` // rotation quaternion w
	Animation     string                 `protobuf:"bytes,8,opt,name=animation,proto3" json:"animation,omitempty"`
	PlatformId    string                 `protobuf:"bytes,9,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStateUpdate) Reset() {
	*x = PlayerStateUpdate{}
	mi := &file_shared_proto_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStateUpdate) ProtoMessage() {}

func (x *PlayerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStateUpdate.ProtoReflect.Descriptor instead.
func (*PlayerStateUpdate) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerStateUpdate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerStateUpdate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerStateUpdate) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerStateUpdate) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *PlayerStateUpdate) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *PlayerStateUpdate) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

func (x *PlayerStateUpdate) GetRw() float32 {
	if x != nil {
		return x.Rw
	}
	return 0
}

func (x *PlayerStateUpdate) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *PlayerStateUpdate) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

type HitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitEvent) Reset() {
	*x = HitEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitEvent) ProtoMessage() {}

func (x *HitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitEvent.ProtoReflect.Descriptor instead.
func (*HitEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{2}
}

func (x *HitEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *HitEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type FireEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireEvent) Reset() {
	*x = FireEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireEvent) ProtoMessage() {}

func (x *FireEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireEvent.ProtoReflect.Descriptor instead.
func (*FireEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{3}
}

type ReloadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadEvent) Reset() {
	*x = ReloadEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadEvent) ProtoMessage() {}

func (x *ReloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadEvent.ProtoReflect.Descriptor instead.
func (*ReloadEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{4}
}

type SwitchWeaponEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeaponId      string                 `protobuf:"bytes,1,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchWeaponEvent) Reset() {
	*x = SwitchWeaponEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchWeaponEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchWeaponEvent) ProtoMessage() {}

func (x *SwitchWeaponEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchWeaponEvent.ProtoReflect.Descriptor instead.
func (*SwitchWeaponEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchWeaponEvent) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

type RespawnRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespawnRequestEvent) Reset() {
	*x = RespawnRequestEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespawnRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespawnRequestEvent) ProtoMessage() {}

func (x *RespawnRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespawnRequestEvent.ProtoReflect.Descriptor instead.
func (*RespawnRequestEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{6}
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_GameState
	//	*ServerMessage_ServerEvent
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_shared_proto_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{7}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerMessage) GetServerEvent() *ServerEvent {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ServerEvent); ok {
			return x.ServerEvent
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_GameState struct {
	GameState *GameState `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerMessage_ServerEvent struct {
	ServerEvent *ServerEvent `protobuf:"bytes,2,opt,name=server_event,json=serverEvent,proto3,oneof"`
}

func (*ServerMessage_GameState) isServerMessage_Message() {}

func (*ServerMessage_ServerEvent) isServerMessage_Message() {}

type GameState struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Players       map[string]*PlayerState `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_shared_proto_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{8}
}

func (x *GameState) GetPlayers() map[string]*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rx            float32                `protobuf:"fixed32,4,opt,name=rx,proto3" json:"rx,omitempty"`
	Ry            float32                `protobuf:"fixed32,5,opt,name=ry,proto3" json:"ry,omitempty"`
	Rz            float32                `protobuf:"fixed32,6,opt,name=rz,proto3" json:"rz,omitempty"`
	Rw            float32                `protobuf:"fixed32,7,opt,name=rw,proto3" json:"rw,omitempty"`
	Animation     string                 `protobuf:"bytes,8,opt,name=animation,proto3" json:"animation,omitempty"`
	Health        int32                  `protobuf:"varint,9,opt,name=health,proto3" json:"health,omitempty"`
	Kills         int32                  `protobuf:"varint,10,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,11,opt,name=deaths,proto3" json:"deaths,omitempty"`
	IsDead        bool                   `protobuf:"varint,12,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	PlatformId    string                 `protobuf:"bytes,13,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_shared_proto_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{9}
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *PlayerState) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *PlayerState) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

func (x *PlayerState) GetRw() float32 {
	if x != nil {
		return x.Rw
	}
	return 0
}

func (x *PlayerState) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *PlayerState) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerState) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerState) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerState) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

func (x *PlayerState) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Respawn
	//	*ServerEvent_Fire
	//	*ServerEvent_HitConfirmed
	//	*ServerEvent_KillConfirmed
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{10}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetRespawn() *RespawnEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Respawn); ok {
			return x.Respawn
		}
	}
	return nil
}

func (x *ServerEvent) GetFire() *ServerFireEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Fire); ok {
			return x.Fire
		}
	}
	return nil
}

func (x *ServerEvent) GetHitConfirmed() *HitConfirmedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_HitConfirmed); ok {
			return x.HitConfirmed
		}
	}
	return nil
}

func (x *ServerEvent) GetKillConfirmed() *KillConfirmedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_KillConfirmed); ok {
			return x.KillConfirmed
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Respawn struct {
	Respawn *RespawnEvent `protobuf:"bytes,1,opt,name=respawn,proto3,oneof"`
}

type ServerEvent_Fire struct {
	Fire *ServerFireEvent `protobuf:"bytes,2,opt,name=fire,proto3,oneof"`
}

type ServerEvent_HitConfirmed struct {
	HitConfirmed *HitConfirmedEvent `protobuf:"bytes,3,opt,name=hit_confirmed,json=hitConfirmed,proto3,oneof"`
}

type ServerEvent_KillConfirmed struct {
	KillConfirmed *KillConfirmedEvent `protobuf:"bytes,4,opt,name=kill_confirmed,json=killConfirmed,proto3,oneof"`
}

func (*ServerEvent_Respawn) isServerEvent_Event() {}

func (*ServerEvent_Fire) isServerEvent_Event() {}

func (*ServerEvent_HitConfirmed) isServerEvent_Event() {}

func (*ServerEvent_KillConfirmed) isServerEvent_Event() {}

type RespawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespawnEvent) Reset() {
	*x = RespawnEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespawnEvent) ProtoMessage() {}

func (x *RespawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespawnEvent.ProtoReflect.Descriptor instead.
func (*RespawnEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{11}
}

func (x *RespawnEvent) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RespawnEvent) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RespawnEvent) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ServerFireEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShooterId     string                 `protobuf:"bytes,1,opt,name=shooter_id,json=shooterId,proto3" json:"shooter_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFireEvent) Reset() {
	*x = ServerFireEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFireEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFireEvent) ProtoMessage() {}

func (x *ServerFireEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFireEvent.ProtoReflect.Descriptor instead.
func (*ServerFireEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{12}
}

func (x *ServerFireEvent) GetShooterId() string {
	if x != nil {
		return x.ShooterId
	}
	return ""
}

type HitConfirmedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitConfirmedEvent) Reset() {
	*x = HitConfirmedEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitConfirmedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitConfirmedEvent) ProtoMessage() {}

func (x *HitConfirmedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitConfirmedEvent.ProtoReflect.Descriptor instead.
func (*HitConfirmedEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{13}
}

type KillConfirmedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillConfirmedEvent) Reset() {
	*x = KillConfirmedEvent{}
	mi := &file_shared_proto_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillConfirmedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillConfirmedEvent) ProtoMessage() {}

func (x *KillConfirmedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillConfirmedEvent.ProtoReflect.Descriptor instead.
func (*KillConfirmedEvent) Descriptor() ([]byte, []int) {
	return file_shared_proto_packets_proto_rawDescGZIP(), []int{14}
}

var File_shared_proto_packets_proto protoreflect.FileDescriptor

const file_shared_proto_packets_proto_rawDesc = "" +
	"\n" +
	"\x1ashared/proto/packets.proto\x12\awarbase\"\xe4\x02\n" +
	"\vClientEvent\x12?\n" +
	"\fstate_update\x18\x01 \x01(\v2\x1a.warbase.PlayerStateUpdateH\x00R\vstateUpdate\x12%\n" +
	"\x03hit\x18\x02 \x01(\v2\x11.warbase.HitEventH\x00R\x03hit\x12(\n" +
	"\x04fire\x18\x03 \x01(\v2\x12.warbase.FireEventH\x00R\x04fire\x12.\n" +
	"\x06reload\x18\x04 \x01(\v2\x14.warbase.ReloadEventH\x00R\x06reload\x12A\n" +
	"\rswitch_weapon\x18\x05 \x01(\v2\x1a.warbase.SwitchWeaponEventH\x00R\fswitchWeapon\x12G\n" +
	"\x0frespawn_request\x18\x06 \x01(\v2\x1c.warbase.RespawnRequestEventH\x00R\x0erespawnRequestB\a\n" +
	"\x05event\"\xbc\x01\n" +
	"\x11PlayerStateUpdate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02rx\x18\x04 \x01(\x02R\x02rx\x12\x0e\n" +
	"\x02ry\x18\x05 \x01(\x02R\x02ry\x12\x0e\n" +
	"\x02rz\x18\x06 \x01(\x02R\x02rz\x12\x0e\n" +
	"\x02rw\x18\a \x01(\x02R\x02rw\x12\x1c\n" +
	"\tanimation\x18\b \x01(\tR\tanimation\x12\x1f\n" +
	"\vplatform_id\x18\t \x01(\tR\n" +
	"platformId\"?\n" +
	"\bHitEvent\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x05R\x06damage\"\v\n" +
	"\tFireEvent\"\r\n" +
	"\vReloadEvent\"0\n" +
	"\x11SwitchWeaponEvent\x12\x1b\n" +
	"\tweapon_id\x18\x01 \x01(\tR\bweaponId\"\x15\n" +
	"\x13RespawnRequestEvent\"\x8a\x01\n" +
	"\rServerMessage\x123\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x12.warbase.GameStateH\x00R\tgameState\x129\n" +
	"\fserver_event\x18\x02 \x01(\v2\x14.warbase.ServerEventH\x00R\vserverEventB\t\n" +
	"\amessage\"\x98\x01\n" +
	"\tGameState\x129\n" +
	"\aplayers\x18\x01 \x03(\v2\x1f.warbase.GameState.PlayersEntryR\aplayers\x1aP\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.warbase.PlayerStateR\x05value:\x028\x01\"\x95\x02\n" +
	"\vPlayerState\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02rx\x18\x04 \x01(\x02R\x02rx\x12\x0e\n" +
	"\x02ry\x18\x05 \x01(\x02R\x02ry\x12\x0e\n" +
	"\x02rz\x18\x06 \x01(\x02R\x02rz\x12\x0e\n" +
	"\x02rw\x18\a \x01(\x02R\x02rw\x12\x1c\n" +
	"\tanimation\x18\b \x01(\tR\tanimation\x12\x16\n" +
	"\x06health\x18\t \x01(\x05R\x06health\x12\x14\n" +
	"\x05kills\x18\n" +
	" \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\v \x01(\x05R\x06deaths\x12\x17\n" +
	"\ais_dead\x18\f \x01(\bR\x06isDead\x12\x1f\n" +
	"\vplatform_id\x18\r \x01(\tR\n" +
	"platformId\"\x82\x02\n" +
	"\vServerEvent\x121\n" +
	"\arespawn\x18\x01 \x01(\v2\x15.warbase.RespawnEventH\x00R\arespawn\x12.\n" +
	"\x04fire\x18\x02 \x01(\v2\x18.warbase.ServerFireEventH\x00R\x04fire\x12A\n" +
	"\rhit_confirmed\x18\x03 \x01(\v2\x1a.warbase.HitConfirmedEventH\x00R\fhitConfirmed\x12D\n" +
	"\x0ekill_confirmed\x18\x04 \x01(\v2\x1b.warbase.KillConfirmedEventH\x00R\rkillConfirmedB\a\n" +
	"\x05event\"8\n" +
	"\fRespawnEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"0\n" +
	"\x0fServerFireEvent\x12\x1d\n" +
	"\n" +
	"shooter_id\x18\x01 \x01(\tR\tshooterId\"\x13\n" +
	"\x11HitConfirmedEvent\"\x14\n" +
	"\x12KillConfirmedEventB'Z%warbase-server/internal/engine;engineb\x06proto3"

var (
	file_shared_proto_packets_proto_rawDescOnce sync.Once
	file_shared_proto_packets_proto_rawDescData []byte
)

func file_shared_proto_packets_proto_rawDescGZIP() []byte {
	file_shared_proto_packets_proto_rawDescOnce.Do(func() {
		file_shared_proto_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_packets_proto_rawDesc), len(file_shared_proto_packets_proto_rawDesc)))
	})
	return file_shared_proto_packets_proto_rawDescData
}

var file_shared_proto_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_shared_proto_packets_proto_goTypes = []any{
	(*ClientEvent)(nil),         // 0: warbase.ClientEvent
	(*PlayerStateUpdate)(nil),   // 1: warbase.PlayerStateUpdate
	(*HitEvent)(nil),            // 2: warbase.HitEvent
	(*FireEvent)(nil),           // 3: warbase.FireEvent
	(*ReloadEvent)(nil),         // 4: warbase.ReloadEvent
	(*SwitchWeaponEvent)(nil),   // 5: warbase.SwitchWeaponEvent
	(*RespawnRequestEvent)(nil), // 6: warbase.RespawnRequestEvent
	(*ServerMessage)(nil),       // 7: warbase.ServerMessage
	(*GameState)(nil),           // 8: warbase.GameState
	(*PlayerState)(nil),         // 9: warbase.PlayerState
	(*ServerEvent)(nil),         // 10: warbase.ServerEvent
	(*RespawnEvent)(nil),        // 11: warbase.RespawnEvent
	(*ServerFireEvent)(nil),     // 12: warbase.ServerFireEvent
	(*HitConfirmedEvent)(nil),   // 13: warbase.HitConfirmedEvent
	(*KillConfirmedEvent)(nil),  // 14: warbase.KillConfirmedEvent
	nil,                         // 15: warbase.GameState.PlayersEntry
}
var file_shared_proto_packets_proto_depIdxs = []int32{
	1,  // 0: warbase.ClientEvent.state_update:type_name -> warbase.PlayerStateUpdate
	2,  // 1: warbase.ClientEvent.hit:type_name -> warbase.HitEvent
	3,  // 2: warbase.ClientEvent.fire:type_name -> warbase.FireEvent
	4,  // 3: warbase.ClientEvent.reload:type_name -> warbase.ReloadEvent
	5,  // 4: warbase.ClientEvent.switch_weapon:type_name -> warbase.SwitchWeaponEvent
	6,  // 5: warbase.ClientEvent.respawn_request:type_name -> warbase.RespawnRequestEvent
	8,  // 6: warbase.ServerMessage.game_state:type_name -> warbase.GameState
	10, // 7: warbase.ServerMessage.server_event:type_name -> warbase.ServerEvent
	15, // 8: warbase.GameState.players:type_name -> warbase.GameState.PlayersEntry
	11, // 9: warbase.ServerEvent.respawn:type_name -> warbase.RespawnEvent
	12, // 10: warbase.ServerEvent.fire:type_name -> warbase.ServerFireEvent
	13, // 11: warbase.ServerEvent.hit_confirmed:type_name -> warbase.HitConfirmedEvent
	14, // 12: warbase.ServerEvent.kill_confirmed:type_name -> warbase.KillConfirmedEvent
	9,  // 13: warbase.GameState.PlayersEntry.value:type_name -> warbase.PlayerState
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_shared_proto_packets_proto_init() }
func file_shared_proto_packets_proto_init() {
	if File_shared_proto_packets_proto != nil {
		return
	}
	file_shared_proto_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_StateUpdate)(nil),
		(*ClientEvent_Hit)(nil),
		(*ClientEvent_Fire)(nil),
		(*ClientEvent_Reload)(nil),
		(*ClientEvent_SwitchWeapon)(nil),
		(*ClientEvent_RespawnRequest)(nil),
	}
	file_shared_proto_packets_proto_msgTypes[7].OneofWrappers = []any{
		(*ServerMessage_GameState)(nil),
		(*ServerMessage_ServerEvent)(nil),
	}
	file_shared_proto_packets_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerEvent_Respawn)(nil),
		(*ServerEvent_Fire)(nil),
		(*ServerEvent_HitConfirmed)(nil),
		(*ServerEvent_KillConfirmed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_packets_proto_rawDesc), len(file_shared_proto_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_shared_proto_packets_proto_goTypes,
		DependencyIndexes: file_shared_proto_packets_proto_depIdxs,
		MessageInfos:      file_shared_proto_packets_proto_msgTypes,
	}.Build()
	File_shared_proto_packets_proto = out.File
	file_shared_proto_packets_proto_goTypes = nil
	file_shared_proto_packets_proto_depIdxs = nil
}
