// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: packets.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClientEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ClientEvent_StateUpdate
	//	*ClientEvent_Hit
	//	*ClientEvent_Fire
	//	*ClientEvent_Reload
	//	*ClientEvent_SwitchWeapon
	//	*ClientEvent_RespawnRequest
	//	*ClientEvent_ThrowGrenade
	//	*ClientEvent_Ping
	Event         isClientEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientEvent) Reset() {
	*x = ClientEvent{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientEvent) ProtoMessage() {}

func (x *ClientEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientEvent.ProtoReflect.Descriptor instead.
func (*ClientEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *ClientEvent) GetEvent() isClientEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ClientEvent) GetStateUpdate() *PlayerStateUpdate {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_StateUpdate); ok {
			return x.StateUpdate
		}
	}
	return nil
}

func (x *ClientEvent) GetHit() *HitEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Hit); ok {
			return x.Hit
		}
	}
	return nil
}

func (x *ClientEvent) GetFire() *FireEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Fire); ok {
			return x.Fire
		}
	}
	return nil
}

func (x *ClientEvent) GetReload() *ReloadEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Reload); ok {
			return x.Reload
		}
	}
	return nil
}

func (x *ClientEvent) GetSwitchWeapon() *SwitchWeaponEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_SwitchWeapon); ok {
			return x.SwitchWeapon
		}
	}
	return nil
}

func (x *ClientEvent) GetRespawnRequest() *RespawnRequestEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_RespawnRequest); ok {
			return x.RespawnRequest
		}
	}
	return nil
}

func (x *ClientEvent) GetThrowGrenade() *ThrowGrenadeEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_ThrowGrenade); ok {
			return x.ThrowGrenade
		}
	}
	return nil
}

func (x *ClientEvent) GetPing() *PingEvent {
	if x != nil {
		if x, ok := x.Event.(*ClientEvent_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientEvent_Event interface {
	isClientEvent_Event()
}

type ClientEvent_StateUpdate struct {
	StateUpdate *PlayerStateUpdate `protobuf:"bytes,1,opt,name=state_update,json=stateUpdate,proto3,oneof"`
}

type ClientEvent_Hit struct {
	Hit *HitEvent `protobuf:"bytes,2,opt,name=hit,proto3,oneof"`
}

type ClientEvent_Fire struct {
	Fire *FireEvent `protobuf:"bytes,3,opt,name=fire,proto3,oneof"`
}

type ClientEvent_Reload struct {
	Reload *ReloadEvent `protobuf:"bytes,4,opt,name=reload,proto3,oneof"`
}

type ClientEvent_SwitchWeapon struct {
	SwitchWeapon *SwitchWeaponEvent `protobuf:"bytes,5,opt,name=switch_weapon,json=switchWeapon,proto3,oneof"`
}

type ClientEvent_RespawnRequest struct {
	RespawnRequest *RespawnRequestEvent `protobuf:"bytes,6,opt,name=respawn_request,json=respawnRequest,proto3,oneof"`
}

type ClientEvent_ThrowGrenade struct {
	ThrowGrenade *ThrowGrenadeEvent `protobuf:"bytes,7,opt,name=throw_grenade,json=throwGrenade,proto3,oneof"`
}

type ClientEvent_Ping struct {
	Ping *PingEvent `protobuf:"bytes,8,opt,name=ping,proto3,oneof"`
}

func (*ClientEvent_StateUpdate) isClientEvent_Event() {}

func (*ClientEvent_Hit) isClientEvent_Event() {}

func (*ClientEvent_Fire) isClientEvent_Event() {}

func (*ClientEvent_Reload) isClientEvent_Event() {}

func (*ClientEvent_SwitchWeapon) isClientEvent_Event() {}

func (*ClientEvent_RespawnRequest) isClientEvent_Event() {}

func (*ClientEvent_ThrowGrenade) isClientEvent_Event() {}

func (*ClientEvent_Ping) isClientEvent_Event() {}

type PlayerStateUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rx            float32                `protobuf:"fixed32,4,opt,name=rx,proto3" json:"rx,omitempty"` // rotation quaternion x
	Ry            float32                `protobuf:"fixed32,5,opt,name=ry,proto3" json:"ry,omitempty"` // rotation quaternion y
	Rz            float32                `protobuf:"fixed32,6,opt,name=rz,proto3" json:"rz,omitempty"` // rotation quaternion z
	Rw            float32                `protobuf:"fixed32,7,opt,name=rw,proto3" json:"rw,omitempty"` // rotation quaternion w
	Animation     string                 `protobuf:"bytes,8,opt,name=animation,proto3" json:"animation,omitempty"`
	PlatformId    string                 `protobuf:"bytes,9,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Ping          int32                  `protobuf:"varint,10,opt,name=ping,proto3" json:"ping,omitempty"`
	WeaponId      string                 `protobuf:"bytes,11,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerStateUpdate) Reset() {
	*x = PlayerStateUpdate{}
	mi := &file_packets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerStateUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerStateUpdate) ProtoMessage() {}

func (x *PlayerStateUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerStateUpdate.ProtoReflect.Descriptor instead.
func (*PlayerStateUpdate) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerStateUpdate) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerStateUpdate) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerStateUpdate) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerStateUpdate) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *PlayerStateUpdate) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *PlayerStateUpdate) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

func (x *PlayerStateUpdate) GetRw() float32 {
	if x != nil {
		return x.Rw
	}
	return 0
}

func (x *PlayerStateUpdate) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *PlayerStateUpdate) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *PlayerStateUpdate) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *PlayerStateUpdate) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

type HitEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Damage        int32                  `protobuf:"varint,2,opt,name=damage,proto3" json:"damage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitEvent) Reset() {
	*x = HitEvent{}
	mi := &file_packets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitEvent) ProtoMessage() {}

func (x *HitEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitEvent.ProtoReflect.Descriptor instead.
func (*HitEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{2}
}

func (x *HitEvent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *HitEvent) GetDamage() int32 {
	if x != nil {
		return x.Damage
	}
	return 0
}

type FireEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OriginX       float32                `protobuf:"fixed32,1,opt,name=origin_x,json=originX,proto3" json:"origin_x,omitempty"`
	OriginY       float32                `protobuf:"fixed32,2,opt,name=origin_y,json=originY,proto3" json:"origin_y,omitempty"`
	OriginZ       float32                `protobuf:"fixed32,3,opt,name=origin_z,json=originZ,proto3" json:"origin_z,omitempty"`
	HitX          float32                `protobuf:"fixed32,4,opt,name=hit_x,json=hitX,proto3" json:"hit_x,omitempty"`
	HitY          float32                `protobuf:"fixed32,5,opt,name=hit_y,json=hitY,proto3" json:"hit_y,omitempty"`
	HitZ          float32                `protobuf:"fixed32,6,opt,name=hit_z,json=hitZ,proto3" json:"hit_z,omitempty"`
	NormalX       float32                `protobuf:"fixed32,7,opt,name=normal_x,json=normalX,proto3" json:"normal_x,omitempty"`
	NormalY       float32                `protobuf:"fixed32,8,opt,name=normal_y,json=normalY,proto3" json:"normal_y,omitempty"`
	NormalZ       float32                `protobuf:"fixed32,9,opt,name=normal_z,json=normalZ,proto3" json:"normal_z,omitempty"`
	HitWall       bool                   `protobuf:"varint,10,opt,name=hit_wall,json=hitWall,proto3" json:"hit_wall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FireEvent) Reset() {
	*x = FireEvent{}
	mi := &file_packets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FireEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FireEvent) ProtoMessage() {}

func (x *FireEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FireEvent.ProtoReflect.Descriptor instead.
func (*FireEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{3}
}

func (x *FireEvent) GetOriginX() float32 {
	if x != nil {
		return x.OriginX
	}
	return 0
}

func (x *FireEvent) GetOriginY() float32 {
	if x != nil {
		return x.OriginY
	}
	return 0
}

func (x *FireEvent) GetOriginZ() float32 {
	if x != nil {
		return x.OriginZ
	}
	return 0
}

func (x *FireEvent) GetHitX() float32 {
	if x != nil {
		return x.HitX
	}
	return 0
}

func (x *FireEvent) GetHitY() float32 {
	if x != nil {
		return x.HitY
	}
	return 0
}

func (x *FireEvent) GetHitZ() float32 {
	if x != nil {
		return x.HitZ
	}
	return 0
}

func (x *FireEvent) GetNormalX() float32 {
	if x != nil {
		return x.NormalX
	}
	return 0
}

func (x *FireEvent) GetNormalY() float32 {
	if x != nil {
		return x.NormalY
	}
	return 0
}

func (x *FireEvent) GetNormalZ() float32 {
	if x != nil {
		return x.NormalZ
	}
	return 0
}

func (x *FireEvent) GetHitWall() bool {
	if x != nil {
		return x.HitWall
	}
	return false
}

type ReloadEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReloadEvent) Reset() {
	*x = ReloadEvent{}
	mi := &file_packets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReloadEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReloadEvent) ProtoMessage() {}

func (x *ReloadEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReloadEvent.ProtoReflect.Descriptor instead.
func (*ReloadEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{4}
}

type SwitchWeaponEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WeaponId      string                 `protobuf:"bytes,1,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwitchWeaponEvent) Reset() {
	*x = SwitchWeaponEvent{}
	mi := &file_packets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwitchWeaponEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwitchWeaponEvent) ProtoMessage() {}

func (x *SwitchWeaponEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwitchWeaponEvent.ProtoReflect.Descriptor instead.
func (*SwitchWeaponEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{5}
}

func (x *SwitchWeaponEvent) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

type RespawnRequestEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespawnRequestEvent) Reset() {
	*x = RespawnRequestEvent{}
	mi := &file_packets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespawnRequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespawnRequestEvent) ProtoMessage() {}

func (x *RespawnRequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespawnRequestEvent.ProtoReflect.Descriptor instead.
func (*RespawnRequestEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{6}
}

type ThrowGrenadeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Px            float32                `protobuf:"fixed32,1,opt,name=px,proto3" json:"px,omitempty"`
	Py            float32                `protobuf:"fixed32,2,opt,name=py,proto3" json:"py,omitempty"`
	Pz            float32                `protobuf:"fixed32,3,opt,name=pz,proto3" json:"pz,omitempty"`
	Vx            float32                `protobuf:"fixed32,4,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            float32                `protobuf:"fixed32,5,opt,name=vy,proto3" json:"vy,omitempty"`
	Vz            float32                `protobuf:"fixed32,6,opt,name=vz,proto3" json:"vz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThrowGrenadeEvent) Reset() {
	*x = ThrowGrenadeEvent{}
	mi := &file_packets_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThrowGrenadeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThrowGrenadeEvent) ProtoMessage() {}

func (x *ThrowGrenadeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThrowGrenadeEvent.ProtoReflect.Descriptor instead.
func (*ThrowGrenadeEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{7}
}

func (x *ThrowGrenadeEvent) GetPx() float32 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *ThrowGrenadeEvent) GetPy() float32 {
	if x != nil {
		return x.Py
	}
	return 0
}

func (x *ThrowGrenadeEvent) GetPz() float32 {
	if x != nil {
		return x.Pz
	}
	return 0
}

func (x *ThrowGrenadeEvent) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *ThrowGrenadeEvent) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *ThrowGrenadeEvent) GetVz() float32 {
	if x != nil {
		return x.Vz
	}
	return 0
}

type ServerPongEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerPongEvent) Reset() {
	*x = ServerPongEvent{}
	mi := &file_packets_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerPongEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerPongEvent) ProtoMessage() {}

func (x *ServerPongEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerPongEvent.ProtoReflect.Descriptor instead.
func (*ServerPongEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{8}
}

func (x *ServerPongEvent) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type PingEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientTime    int64                  `protobuf:"varint,1,opt,name=client_time,json=clientTime,proto3" json:"client_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingEvent) Reset() {
	*x = PingEvent{}
	mi := &file_packets_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingEvent) ProtoMessage() {}

func (x *PingEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingEvent.ProtoReflect.Descriptor instead.
func (*PingEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{9}
}

func (x *PingEvent) GetClientTime() int64 {
	if x != nil {
		return x.ClientTime
	}
	return 0
}

type ServerMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ServerMessage_GameState
	//	*ServerMessage_ServerEvent
	Message       isServerMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerMessage) Reset() {
	*x = ServerMessage{}
	mi := &file_packets_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerMessage) ProtoMessage() {}

func (x *ServerMessage) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerMessage.ProtoReflect.Descriptor instead.
func (*ServerMessage) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{10}
}

func (x *ServerMessage) GetMessage() isServerMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ServerMessage) GetGameState() *GameState {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *ServerMessage) GetServerEvent() *ServerEvent {
	if x != nil {
		if x, ok := x.Message.(*ServerMessage_ServerEvent); ok {
			return x.ServerEvent
		}
	}
	return nil
}

type isServerMessage_Message interface {
	isServerMessage_Message()
}

type ServerMessage_GameState struct {
	GameState *GameState `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3,oneof"`
}

type ServerMessage_ServerEvent struct {
	ServerEvent *ServerEvent `protobuf:"bytes,2,opt,name=server_event,json=serverEvent,proto3,oneof"`
}

func (*ServerMessage_GameState) isServerMessage_Message() {}

func (*ServerMessage_ServerEvent) isServerMessage_Message() {}

type GameState struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	Players       map[string]*PlayerState `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_packets_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{11}
}

func (x *GameState) GetPlayers() map[string]*PlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

type PlayerState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	Rx            float32                `protobuf:"fixed32,4,opt,name=rx,proto3" json:"rx,omitempty"`
	Ry            float32                `protobuf:"fixed32,5,opt,name=ry,proto3" json:"ry,omitempty"`
	Rz            float32                `protobuf:"fixed32,6,opt,name=rz,proto3" json:"rz,omitempty"`
	Rw            float32                `protobuf:"fixed32,7,opt,name=rw,proto3" json:"rw,omitempty"`
	Animation     string                 `protobuf:"bytes,8,opt,name=animation,proto3" json:"animation,omitempty"`
	Health        int32                  `protobuf:"varint,9,opt,name=health,proto3" json:"health,omitempty"`
	Kills         int32                  `protobuf:"varint,10,opt,name=kills,proto3" json:"kills,omitempty"`
	Deaths        int32                  `protobuf:"varint,11,opt,name=deaths,proto3" json:"deaths,omitempty"`
	IsDead        bool                   `protobuf:"varint,12,opt,name=is_dead,json=isDead,proto3" json:"is_dead,omitempty"`
	PlatformId    string                 `protobuf:"bytes,13,opt,name=platform_id,json=platformId,proto3" json:"platform_id,omitempty"`
	Ping          int32                  `protobuf:"varint,14,opt,name=ping,proto3" json:"ping,omitempty"`
	WeaponId      string                 `protobuf:"bytes,15,opt,name=weapon_id,json=weaponId,proto3" json:"weapon_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerState) Reset() {
	*x = PlayerState{}
	mi := &file_packets_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerState) ProtoMessage() {}

func (x *PlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerState.ProtoReflect.Descriptor instead.
func (*PlayerState) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{12}
}

func (x *PlayerState) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *PlayerState) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *PlayerState) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

func (x *PlayerState) GetRx() float32 {
	if x != nil {
		return x.Rx
	}
	return 0
}

func (x *PlayerState) GetRy() float32 {
	if x != nil {
		return x.Ry
	}
	return 0
}

func (x *PlayerState) GetRz() float32 {
	if x != nil {
		return x.Rz
	}
	return 0
}

func (x *PlayerState) GetRw() float32 {
	if x != nil {
		return x.Rw
	}
	return 0
}

func (x *PlayerState) GetAnimation() string {
	if x != nil {
		return x.Animation
	}
	return ""
}

func (x *PlayerState) GetHealth() int32 {
	if x != nil {
		return x.Health
	}
	return 0
}

func (x *PlayerState) GetKills() int32 {
	if x != nil {
		return x.Kills
	}
	return 0
}

func (x *PlayerState) GetDeaths() int32 {
	if x != nil {
		return x.Deaths
	}
	return 0
}

func (x *PlayerState) GetIsDead() bool {
	if x != nil {
		return x.IsDead
	}
	return false
}

func (x *PlayerState) GetPlatformId() string {
	if x != nil {
		return x.PlatformId
	}
	return ""
}

func (x *PlayerState) GetPing() int32 {
	if x != nil {
		return x.Ping
	}
	return 0
}

func (x *PlayerState) GetWeaponId() string {
	if x != nil {
		return x.WeaponId
	}
	return ""
}

type ServerEvent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Event:
	//
	//	*ServerEvent_Respawn
	//	*ServerEvent_Fire
	//	*ServerEvent_HitConfirmed
	//	*ServerEvent_KillConfirmed
	//	*ServerEvent_ThrowGrenade
	//	*ServerEvent_Pong
	Event         isServerEvent_Event `protobuf_oneof:"event"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerEvent) Reset() {
	*x = ServerEvent{}
	mi := &file_packets_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerEvent) ProtoMessage() {}

func (x *ServerEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerEvent.ProtoReflect.Descriptor instead.
func (*ServerEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{13}
}

func (x *ServerEvent) GetEvent() isServerEvent_Event {
	if x != nil {
		return x.Event
	}
	return nil
}

func (x *ServerEvent) GetRespawn() *RespawnEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Respawn); ok {
			return x.Respawn
		}
	}
	return nil
}

func (x *ServerEvent) GetFire() *ServerFireEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Fire); ok {
			return x.Fire
		}
	}
	return nil
}

func (x *ServerEvent) GetHitConfirmed() *HitConfirmedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_HitConfirmed); ok {
			return x.HitConfirmed
		}
	}
	return nil
}

func (x *ServerEvent) GetKillConfirmed() *KillConfirmedEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_KillConfirmed); ok {
			return x.KillConfirmed
		}
	}
	return nil
}

func (x *ServerEvent) GetThrowGrenade() *ServerThrowGrenadeEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_ThrowGrenade); ok {
			return x.ThrowGrenade
		}
	}
	return nil
}

func (x *ServerEvent) GetPong() *ServerPongEvent {
	if x != nil {
		if x, ok := x.Event.(*ServerEvent_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

type isServerEvent_Event interface {
	isServerEvent_Event()
}

type ServerEvent_Respawn struct {
	Respawn *RespawnEvent `protobuf:"bytes,1,opt,name=respawn,proto3,oneof"`
}

type ServerEvent_Fire struct {
	Fire *ServerFireEvent `protobuf:"bytes,2,opt,name=fire,proto3,oneof"`
}

type ServerEvent_HitConfirmed struct {
	HitConfirmed *HitConfirmedEvent `protobuf:"bytes,3,opt,name=hit_confirmed,json=hitConfirmed,proto3,oneof"`
}

type ServerEvent_KillConfirmed struct {
	KillConfirmed *KillConfirmedEvent `protobuf:"bytes,4,opt,name=kill_confirmed,json=killConfirmed,proto3,oneof"`
}

type ServerEvent_ThrowGrenade struct {
	ThrowGrenade *ServerThrowGrenadeEvent `protobuf:"bytes,5,opt,name=throw_grenade,json=throwGrenade,proto3,oneof"`
}

type ServerEvent_Pong struct {
	Pong *ServerPongEvent `protobuf:"bytes,6,opt,name=pong,proto3,oneof"`
}

func (*ServerEvent_Respawn) isServerEvent_Event() {}

func (*ServerEvent_Fire) isServerEvent_Event() {}

func (*ServerEvent_HitConfirmed) isServerEvent_Event() {}

func (*ServerEvent_KillConfirmed) isServerEvent_Event() {}

func (*ServerEvent_ThrowGrenade) isServerEvent_Event() {}

func (*ServerEvent_Pong) isServerEvent_Event() {}

type RespawnEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	Z             float32                `protobuf:"fixed32,3,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespawnEvent) Reset() {
	*x = RespawnEvent{}
	mi := &file_packets_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespawnEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespawnEvent) ProtoMessage() {}

func (x *RespawnEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespawnEvent.ProtoReflect.Descriptor instead.
func (*RespawnEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{14}
}

func (x *RespawnEvent) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *RespawnEvent) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *RespawnEvent) GetZ() float32 {
	if x != nil {
		return x.Z
	}
	return 0
}

type ServerFireEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShooterId     string                 `protobuf:"bytes,1,opt,name=shooter_id,json=shooterId,proto3" json:"shooter_id,omitempty"`
	OriginX       float32                `protobuf:"fixed32,2,opt,name=origin_x,json=originX,proto3" json:"origin_x,omitempty"`
	OriginY       float32                `protobuf:"fixed32,3,opt,name=origin_y,json=originY,proto3" json:"origin_y,omitempty"`
	OriginZ       float32                `protobuf:"fixed32,4,opt,name=origin_z,json=originZ,proto3" json:"origin_z,omitempty"`
	HitX          float32                `protobuf:"fixed32,5,opt,name=hit_x,json=hitX,proto3" json:"hit_x,omitempty"`
	HitY          float32                `protobuf:"fixed32,6,opt,name=hit_y,json=hitY,proto3" json:"hit_y,omitempty"`
	HitZ          float32                `protobuf:"fixed32,7,opt,name=hit_z,json=hitZ,proto3" json:"hit_z,omitempty"`
	NormalX       float32                `protobuf:"fixed32,8,opt,name=normal_x,json=normalX,proto3" json:"normal_x,omitempty"`
	NormalY       float32                `protobuf:"fixed32,9,opt,name=normal_y,json=normalY,proto3" json:"normal_y,omitempty"`
	NormalZ       float32                `protobuf:"fixed32,10,opt,name=normal_z,json=normalZ,proto3" json:"normal_z,omitempty"`
	HitWall       bool                   `protobuf:"varint,11,opt,name=hit_wall,json=hitWall,proto3" json:"hit_wall,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerFireEvent) Reset() {
	*x = ServerFireEvent{}
	mi := &file_packets_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerFireEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerFireEvent) ProtoMessage() {}

func (x *ServerFireEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerFireEvent.ProtoReflect.Descriptor instead.
func (*ServerFireEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{15}
}

func (x *ServerFireEvent) GetShooterId() string {
	if x != nil {
		return x.ShooterId
	}
	return ""
}

func (x *ServerFireEvent) GetOriginX() float32 {
	if x != nil {
		return x.OriginX
	}
	return 0
}

func (x *ServerFireEvent) GetOriginY() float32 {
	if x != nil {
		return x.OriginY
	}
	return 0
}

func (x *ServerFireEvent) GetOriginZ() float32 {
	if x != nil {
		return x.OriginZ
	}
	return 0
}

func (x *ServerFireEvent) GetHitX() float32 {
	if x != nil {
		return x.HitX
	}
	return 0
}

func (x *ServerFireEvent) GetHitY() float32 {
	if x != nil {
		return x.HitY
	}
	return 0
}

func (x *ServerFireEvent) GetHitZ() float32 {
	if x != nil {
		return x.HitZ
	}
	return 0
}

func (x *ServerFireEvent) GetNormalX() float32 {
	if x != nil {
		return x.NormalX
	}
	return 0
}

func (x *ServerFireEvent) GetNormalY() float32 {
	if x != nil {
		return x.NormalY
	}
	return 0
}

func (x *ServerFireEvent) GetNormalZ() float32 {
	if x != nil {
		return x.NormalZ
	}
	return 0
}

func (x *ServerFireEvent) GetHitWall() bool {
	if x != nil {
		return x.HitWall
	}
	return false
}

type HitConfirmedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HitConfirmedEvent) Reset() {
	*x = HitConfirmedEvent{}
	mi := &file_packets_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HitConfirmedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HitConfirmedEvent) ProtoMessage() {}

func (x *HitConfirmedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HitConfirmedEvent.ProtoReflect.Descriptor instead.
func (*HitConfirmedEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{16}
}

type KillConfirmedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KillConfirmedEvent) Reset() {
	*x = KillConfirmedEvent{}
	mi := &file_packets_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KillConfirmedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillConfirmedEvent) ProtoMessage() {}

func (x *KillConfirmedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillConfirmedEvent.ProtoReflect.Descriptor instead.
func (*KillConfirmedEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{17}
}

type ServerThrowGrenadeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShooterId     string                 `protobuf:"bytes,1,opt,name=shooter_id,json=shooterId,proto3" json:"shooter_id,omitempty"`
	Px            float32                `protobuf:"fixed32,2,opt,name=px,proto3" json:"px,omitempty"`
	Py            float32                `protobuf:"fixed32,3,opt,name=py,proto3" json:"py,omitempty"`
	Pz            float32                `protobuf:"fixed32,4,opt,name=pz,proto3" json:"pz,omitempty"`
	Vx            float32                `protobuf:"fixed32,5,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy            float32                `protobuf:"fixed32,6,opt,name=vy,proto3" json:"vy,omitempty"`
	Vz            float32                `protobuf:"fixed32,7,opt,name=vz,proto3" json:"vz,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerThrowGrenadeEvent) Reset() {
	*x = ServerThrowGrenadeEvent{}
	mi := &file_packets_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerThrowGrenadeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerThrowGrenadeEvent) ProtoMessage() {}

func (x *ServerThrowGrenadeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerThrowGrenadeEvent.ProtoReflect.Descriptor instead.
func (*ServerThrowGrenadeEvent) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{18}
}

func (x *ServerThrowGrenadeEvent) GetShooterId() string {
	if x != nil {
		return x.ShooterId
	}
	return ""
}

func (x *ServerThrowGrenadeEvent) GetPx() float32 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *ServerThrowGrenadeEvent) GetPy() float32 {
	if x != nil {
		return x.Py
	}
	return 0
}

func (x *ServerThrowGrenadeEvent) GetPz() float32 {
	if x != nil {
		return x.Pz
	}
	return 0
}

func (x *ServerThrowGrenadeEvent) GetVx() float32 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *ServerThrowGrenadeEvent) GetVy() float32 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *ServerThrowGrenadeEvent) GetVz() float32 {
	if x != nil {
		return x.Vz
	}
	return 0
}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\awarbase\"\xd1\x03\n" +
	"\vClientEvent\x12?\n" +
	"\fstate_update\x18\x01 \x01(\v2\x1a.warbase.PlayerStateUpdateH\x00R\vstateUpdate\x12%\n" +
	"\x03hit\x18\x02 \x01(\v2\x11.warbase.HitEventH\x00R\x03hit\x12(\n" +
	"\x04fire\x18\x03 \x01(\v2\x12.warbase.FireEventH\x00R\x04fire\x12.\n" +
	"\x06reload\x18\x04 \x01(\v2\x14.warbase.ReloadEventH\x00R\x06reload\x12A\n" +
	"\rswitch_weapon\x18\x05 \x01(\v2\x1a.warbase.SwitchWeaponEventH\x00R\fswitchWeapon\x12G\n" +
	"\x0frespawn_request\x18\x06 \x01(\v2\x1c.warbase.RespawnRequestEventH\x00R\x0erespawnRequest\x12A\n" +
	"\rthrow_grenade\x18\a \x01(\v2\x1a.warbase.ThrowGrenadeEventH\x00R\fthrowGrenade\x12(\n" +
	"\x04ping\x18\b \x01(\v2\x12.warbase.PingEventH\x00R\x04pingB\a\n" +
	"\x05event\"\xed\x01\n" +
	"\x11PlayerStateUpdate\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02rx\x18\x04 \x01(\x02R\x02rx\x12\x0e\n" +
	"\x02ry\x18\x05 \x01(\x02R\x02ry\x12\x0e\n" +
	"\x02rz\x18\x06 \x01(\x02R\x02rz\x12\x0e\n" +
	"\x02rw\x18\a \x01(\x02R\x02rw\x12\x1c\n" +
	"\tanimation\x18\b \x01(\tR\tanimation\x12\x1f\n" +
	"\vplatform_id\x18\t \x01(\tR\n" +
	"platformId\x12\x12\n" +
	"\x04ping\x18\n" +
	" \x01(\x05R\x04ping\x12\x1b\n" +
	"\tweapon_id\x18\v \x01(\tR\bweaponId\"?\n" +
	"\bHitEvent\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x16\n" +
	"\x06damage\x18\x02 \x01(\x05R\x06damage\"\x87\x02\n" +
	"\tFireEvent\x12\x19\n" +
	"\borigin_x\x18\x01 \x01(\x02R\aoriginX\x12\x19\n" +
	"\borigin_y\x18\x02 \x01(\x02R\aoriginY\x12\x19\n" +
	"\borigin_z\x18\x03 \x01(\x02R\aoriginZ\x12\x13\n" +
	"\x05hit_x\x18\x04 \x01(\x02R\x04hitX\x12\x13\n" +
	"\x05hit_y\x18\x05 \x01(\x02R\x04hitY\x12\x13\n" +
	"\x05hit_z\x18\x06 \x01(\x02R\x04hitZ\x12\x19\n" +
	"\bnormal_x\x18\a \x01(\x02R\anormalX\x12\x19\n" +
	"\bnormal_y\x18\b \x01(\x02R\anormalY\x12\x19\n" +
	"\bnormal_z\x18\t \x01(\x02R\anormalZ\x12\x19\n" +
	"\bhit_wall\x18\n" +
	" \x01(\bR\ahitWall\"\r\n" +
	"\vReloadEvent\"0\n" +
	"\x11SwitchWeaponEvent\x12\x1b\n" +
	"\tweapon_id\x18\x01 \x01(\tR\bweaponId\"\x15\n" +
	"\x13RespawnRequestEvent\"s\n" +
	"\x11ThrowGrenadeEvent\x12\x0e\n" +
	"\x02px\x18\x01 \x01(\x02R\x02px\x12\x0e\n" +
	"\x02py\x18\x02 \x01(\x02R\x02py\x12\x0e\n" +
	"\x02pz\x18\x03 \x01(\x02R\x02pz\x12\x0e\n" +
	"\x02vx\x18\x04 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x05 \x01(\x02R\x02vy\x12\x0e\n" +
	"\x02vz\x18\x06 \x01(\x02R\x02vz\"2\n" +
	"\x0fServerPongEvent\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\",\n" +
	"\tPingEvent\x12\x1f\n" +
	"\vclient_time\x18\x01 \x01(\x03R\n" +
	"clientTime\"\x8a\x01\n" +
	"\rServerMessage\x123\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x12.warbase.GameStateH\x00R\tgameState\x129\n" +
	"\fserver_event\x18\x02 \x01(\v2\x14.warbase.ServerEventH\x00R\vserverEventB\t\n" +
	"\amessage\"\x98\x01\n" +
	"\tGameState\x129\n" +
	"\aplayers\x18\x01 \x03(\v2\x1f.warbase.GameState.PlayersEntryR\aplayers\x1aP\n" +
	"\fPlayersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12*\n" +
	"\x05value\x18\x02 \x01(\v2\x14.warbase.PlayerStateR\x05value:\x028\x01\"\xc6\x02\n" +
	"\vPlayerState\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\x12\x0e\n" +
	"\x02rx\x18\x04 \x01(\x02R\x02rx\x12\x0e\n" +
	"\x02ry\x18\x05 \x01(\x02R\x02ry\x12\x0e\n" +
	"\x02rz\x18\x06 \x01(\x02R\x02rz\x12\x0e\n" +
	"\x02rw\x18\a \x01(\x02R\x02rw\x12\x1c\n" +
	"\tanimation\x18\b \x01(\tR\tanimation\x12\x16\n" +
	"\x06health\x18\t \x01(\x05R\x06health\x12\x14\n" +
	"\x05kills\x18\n" +
	" \x01(\x05R\x05kills\x12\x16\n" +
	"\x06deaths\x18\v \x01(\x05R\x06deaths\x12\x17\n" +
	"\ais_dead\x18\f \x01(\bR\x06isDead\x12\x1f\n" +
	"\vplatform_id\x18\r \x01(\tR\n" +
	"platformId\x12\x12\n" +
	"\x04ping\x18\x0e \x01(\x05R\x04ping\x12\x1b\n" +
	"\tweapon_id\x18\x0f \x01(\tR\bweaponId\"\xfb\x02\n" +
	"\vServerEvent\x121\n" +
	"\arespawn\x18\x01 \x01(\v2\x15.warbase.RespawnEventH\x00R\arespawn\x12.\n" +
	"\x04fire\x18\x02 \x01(\v2\x18.warbase.ServerFireEventH\x00R\x04fire\x12A\n" +
	"\rhit_confirmed\x18\x03 \x01(\v2\x1a.warbase.HitConfirmedEventH\x00R\fhitConfirmed\x12D\n" +
	"\x0ekill_confirmed\x18\x04 \x01(\v2\x1b.warbase.KillConfirmedEventH\x00R\rkillConfirmed\x12G\n" +
	"\rthrow_grenade\x18\x05 \x01(\v2 .warbase.ServerThrowGrenadeEventH\x00R\fthrowGrenade\x12.\n" +
	"\x04pong\x18\x06 \x01(\v2\x18.warbase.ServerPongEventH\x00R\x04pongB\a\n" +
	"\x05event\"8\n" +
	"\fRespawnEvent\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01y\x12\f\n" +
	"\x01z\x18\x03 \x01(\x02R\x01z\"\xac\x02\n" +
	"\x0fServerFireEvent\x12\x1d\n" +
	"\n" +
	"shooter_id\x18\x01 \x01(\tR\tshooterId\x12\x19\n" +
	"\borigin_x\x18\x02 \x01(\x02R\aoriginX\x12\x19\n" +
	"\borigin_y\x18\x03 \x01(\x02R\aoriginY\x12\x19\n" +
	"\borigin_z\x18\x04 \x01(\x02R\aoriginZ\x12\x13\n" +
	"\x05hit_x\x18\x05 \x01(\x02R\x04hitX\x12\x13\n" +
	"\x05hit_y\x18\x06 \x01(\x02R\x04hitY\x12\x13\n" +
	"\x05hit_z\x18\a \x01(\x02R\x04hitZ\x12\x19\n" +
	"\bnormal_x\x18\b \x01(\x02R\anormalX\x12\x19\n" +
	"\bnormal_y\x18\t \x01(\x02R\anormalY\x12\x19\n" +
	"\bnormal_z\x18\n" +
	" \x01(\x02R\anormalZ\x12\x19\n" +
	"\bhit_wall\x18\v \x01(\bR\ahitWall\"\x13\n" +
	"\x11HitConfirmedEvent\"\x14\n" +
	"\x12KillConfirmedEvent\"\x98\x01\n" +
	"\x17ServerThrowGrenadeEvent\x12\x1d\n" +
	"\n" +
	"shooter_id\x18\x01 \x01(\tR\tshooterId\x12\x0e\n" +
	"\x02px\x18\x02 \x01(\x02R\x02px\x12\x0e\n" +
	"\x02py\x18\x03 \x01(\x02R\x02py\x12\x0e\n" +
	"\x02pz\x18\x04 \x01(\x02R\x02pz\x12\x0e\n" +
	"\x02vx\x18\x05 \x01(\x02R\x02vx\x12\x0e\n" +
	"\x02vy\x18\x06 \x01(\x02R\x02vy\x12\x0e\n" +
	"\x02vz\x18\a \x01(\x02R\x02vzB'Z%warbase-server/internal/engine;engineb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_packets_proto_goTypes = []any{
	(*ClientEvent)(nil),             // 0: warbase.ClientEvent
	(*PlayerStateUpdate)(nil),       // 1: warbase.PlayerStateUpdate
	(*HitEvent)(nil),                // 2: warbase.HitEvent
	(*FireEvent)(nil),               // 3: warbase.FireEvent
	(*ReloadEvent)(nil),             // 4: warbase.ReloadEvent
	(*SwitchWeaponEvent)(nil),       // 5: warbase.SwitchWeaponEvent
	(*RespawnRequestEvent)(nil),     // 6: warbase.RespawnRequestEvent
	(*ThrowGrenadeEvent)(nil),       // 7: warbase.ThrowGrenadeEvent
	(*ServerPongEvent)(nil),         // 8: warbase.ServerPongEvent
	(*PingEvent)(nil),               // 9: warbase.PingEvent
	(*ServerMessage)(nil),           // 10: warbase.ServerMessage
	(*GameState)(nil),               // 11: warbase.GameState
	(*PlayerState)(nil),             // 12: warbase.PlayerState
	(*ServerEvent)(nil),             // 13: warbase.ServerEvent
	(*RespawnEvent)(nil),            // 14: warbase.RespawnEvent
	(*ServerFireEvent)(nil),         // 15: warbase.ServerFireEvent
	(*HitConfirmedEvent)(nil),       // 16: warbase.HitConfirmedEvent
	(*KillConfirmedEvent)(nil),      // 17: warbase.KillConfirmedEvent
	(*ServerThrowGrenadeEvent)(nil), // 18: warbase.ServerThrowGrenadeEvent
	nil,                             // 19: warbase.GameState.PlayersEntry
}
var file_packets_proto_depIdxs = []int32{
	1,  // 0: warbase.ClientEvent.state_update:type_name -> warbase.PlayerStateUpdate
	2,  // 1: warbase.ClientEvent.hit:type_name -> warbase.HitEvent
	3,  // 2: warbase.ClientEvent.fire:type_name -> warbase.FireEvent
	4,  // 3: warbase.ClientEvent.reload:type_name -> warbase.ReloadEvent
	5,  // 4: warbase.ClientEvent.switch_weapon:type_name -> warbase.SwitchWeaponEvent
	6,  // 5: warbase.ClientEvent.respawn_request:type_name -> warbase.RespawnRequestEvent
	7,  // 6: warbase.ClientEvent.throw_grenade:type_name -> warbase.ThrowGrenadeEvent
	9,  // 7: warbase.ClientEvent.ping:type_name -> warbase.PingEvent
	11, // 8: warbase.ServerMessage.game_state:type_name -> warbase.GameState
	13, // 9: warbase.ServerMessage.server_event:type_name -> warbase.ServerEvent
	19, // 10: warbase.GameState.players:type_name -> warbase.GameState.PlayersEntry
	14, // 11: warbase.ServerEvent.respawn:type_name -> warbase.RespawnEvent
	15, // 12: warbase.ServerEvent.fire:type_name -> warbase.ServerFireEvent
	16, // 13: warbase.ServerEvent.hit_confirmed:type_name -> warbase.HitConfirmedEvent
	17, // 14: warbase.ServerEvent.kill_confirmed:type_name -> warbase.KillConfirmedEvent
	18, // 15: warbase.ServerEvent.throw_grenade:type_name -> warbase.ServerThrowGrenadeEvent
	8,  // 16: warbase.ServerEvent.pong:type_name -> warbase.ServerPongEvent
	12, // 17: warbase.GameState.PlayersEntry.value:type_name -> warbase.PlayerState
	18, // [18:18] is the sub-list for method output_type
	18, // [18:18] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*ClientEvent_StateUpdate)(nil),
		(*ClientEvent_Hit)(nil),
		(*ClientEvent_Fire)(nil),
		(*ClientEvent_Reload)(nil),
		(*ClientEvent_SwitchWeapon)(nil),
		(*ClientEvent_RespawnRequest)(nil),
		(*ClientEvent_ThrowGrenade)(nil),
		(*ClientEvent_Ping)(nil),
	}
	file_packets_proto_msgTypes[10].OneofWrappers = []any{
		(*ServerMessage_GameState)(nil),
		(*ServerMessage_ServerEvent)(nil),
	}
	file_packets_proto_msgTypes[13].OneofWrappers = []any{
		(*ServerEvent_Respawn)(nil),
		(*ServerEvent_Fire)(nil),
		(*ServerEvent_HitConfirmed)(nil),
		(*ServerEvent_KillConfirmed)(nil),
		(*ServerEvent_ThrowGrenade)(nil),
		(*ServerEvent_Pong)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
